# This file is generated by .github/workflows/release.yml. Do not edit by hand.
class Hop < Formula
  desc "Fast full-text search and resume for coding-agent sessions"
  homepage "https://github.com/amittamari/hop"
  version "0.2.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/amittamari/hop/releases/download/v0.2.3/hop-0.2.3-aarch64-apple-darwin.tar.gz"
      sha256 "27447eff68b2800892293733146c2619f79384e648ecbef962ff30196b34c5d7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/amittamari/hop/releases/download/v0.2.3/hop-0.2.3-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "8742ee223b30970f5b4b98643608bfe621d7d747ed335d6ecfc956ca24171a82"
    end
    on_intel do
      url "https://github.com/amittamari/hop/releases/download/v0.2.3/hop-0.2.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b400e4aa00983bac31f0bb9153fd984214dee382fffbd057f2d42a2929a77ae3"
    end
  end

  def install
    bin.install "hop"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hop --version")
  end
end
