# This file is generated by .github/workflows/release.yml. Do not edit by hand.
class Hop < Formula
  desc "Fast full-text search and resume for coding-agent sessions"
  homepage "https://github.com/amittamari/hop"
  version "0.2.5"
  license "MIT"

  depends_on "gh" => :recommended

  on_macos do
    on_arm do
      url "https://github.com/amittamari/hop/releases/download/v0.2.5/hop-0.2.5-aarch64-apple-darwin.tar.gz"
      sha256 "ed6cc6a7679f4f1b37bc81d946fc5a89cbdbefbacc72fd7705e0a68ed35a3e7d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/amittamari/hop/releases/download/v0.2.5/hop-0.2.5-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1d4a5a0ea3fffed32129ffc3b929dea78bf5d5c31991d4004f334255da935ab3"
    end
    on_intel do
      url "https://github.com/amittamari/hop/releases/download/v0.2.5/hop-0.2.5-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "55c204df45744a473f83afd8c9dac8076fbd19aa5b26c7509148c6c4b6ccf03d"
    end
  end

  def install
    bin.install "hop"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hop --version")
  end
end
